version: '3.8'

networks:
  default:

services:
  server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    build: 
      context: ../src
      dockerfile: server/Server/Dockerfile
    ports:
      - ${ServerPort:-7207}:443
    networks:
      - default
    env_file:
      - certificates.env
      - service-urls.env
      - service-mappings.env
    volumes:
      - ~/.aspnet/https:/home/app/.aspnet/https
      - ~/.aspnet/DataProtection-Keys:/home/app/.aspnet/DataProtection-Keys
    environment:
      ASPNETCORE_HTTP_PORTS: 
      ASPNETCORE_HTTPS_PORTS: 443
      ASPNETCORE_ENVIRONMENT: Staging

  ticker:
    container_name: ${COMPOSE_PROJECT_NAME}-ticker
    build: 
      context: ../src
      dockerfile: server/Ticker/Dockerfile
    ports:
      - ${TickerPort:-7206}:443
    networks:
      - default
    depends_on:
      server:
        condition: service_started
    env_file:
      - certificates.env
      - service-urls.env
      - service-mappings.env
    volumes:
      - ~/.aspnet/https:/home/app/.aspnet/https
      - ~/.aspnet/DataProtection-Keys:/home/app/.aspnet/DataProtection-Keys
    environment:
      ASPNETCORE_HTTP_PORTS: 
      ASPNETCORE_HTTPS_PORTS: 443
      ASPNETCORE_ENVIRONMENT: Staging

  portal:
    container_name: ${COMPOSE_PROJECT_NAME}-portal
    build: 
      context: ../src
      dockerfile: frontend/Portal/Dockerfile
    ports:
      - 5015:80
      - ${PortalPort:-7053}:443
    networks:
      - default
    depends_on:
      server:
        condition: service_started
    env_file:
      - certificates.env
      - service-urls.env
      - service-mappings.env
    volumes:
      - ~/.aspnet/https:/home/app/.aspnet/https/
      - ~/.aspnet/DataProtection-Keys:/home/app/.aspnet/DataProtection-Keys
    environment:
      ASPNETCORE_HTTP_PORTS: 80
      ASPNETCORE_HTTPS_PORTS: 443
      ASPNETCORE_HTTPS_REDIRECT_PORT: ${PortalPort:-7053}
      ASPNETCORE_ENVIRONMENT: Staging

  swagger:
    container_name: ${COMPOSE_PROJECT_NAME}-swagger
    build: 
      context: ../src
      dockerfile: frontend/Swagger/Dockerfile
    ports:
      - 5108:80
      - ${SwaggerPort:-7272}:443
    networks:
      - default
    depends_on:
      portal:
        condition: service_started
      server:
        condition: service_started
      ticker:
        condition: service_started
    env_file:
      - certificates.env
      - service-urls.env
      - service-mappings.env
    volumes:
      - ~/.aspnet/https:/home/app/.aspnet/https/
      - ~/.aspnet/DataProtection-Keys:/home/app/.aspnet/DataProtection-Keys
    environment:
      ASPNETCORE_HTTP_PORTS: 80
      ASPNETCORE_HTTPS_PORTS: 443
      ASPNETCORE_HTTPS_REDIRECT_PORT: ${SwaggerPort:-7272}
      ASPNETCORE_ENVIRONMENT: Staging

  dev-log:
    container_name: ${COMPOSE_PROJECT_NAME}-dev-log
    build: 
      context: ../src
      dockerfile: frontend/DevLog/Dockerfile
    ports:
      - 5213:80
      - ${DevLogPort:-7190}:443
    networks:
      - default
    depends_on:
      portal:
        condition: service_started
    env_file:
      - certificates.env
      - service-urls.env
      - service-mappings.env
    volumes:
      - ~/.aspnet/https:/home/app/.aspnet/https/
      - ~/.aspnet/DataProtection-Keys:/home/app/.aspnet/DataProtection-Keys
    environment:
      ASPNETCORE_HTTP_PORTS: 80
      ASPNETCORE_HTTPS_PORTS: 443
      ASPNETCORE_HTTPS_REDIRECT_PORT: ${DevLogPort:-7190}
      ASPNETCORE_ENVIRONMENT: Staging
      