version: '3.8'

name: "multitenancy-monolith"

networks:
  redis:

services:

  redis:    
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: cschulzsuper/mm-redis:dev
    build: 
      context: redis
      dockerfile: Dockerfile
    environment:
      - REDIS_PASSWORD=default
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - redis    
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s